/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.multclin.telas;

/**
 *
 * @author Pessoal
 */
public class Caixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Caixa
     */
    public Caixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelSobreMedico = new javax.swing.JPanel();
        lblRepositNomeMedicoAgenda = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        lblEspecialidades = new javax.swing.JLabel();
        lblIdMedicoAgenda = new javax.swing.JLabel();
        cbEspecialidadeAgenda = new javax.swing.JLabel();
        painelPaciente1 = new javax.swing.JPanel();
        lblRepositIdPacienteAgenda = new javax.swing.JLabel();
        lblRepositPacienteAgenda = new javax.swing.JLabel();
        lblNomePaciente = new javax.swing.JLabel();
        lblDtNascimento = new javax.swing.JLabel();
        lblRepositDtNascimentoAgenda = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblRepositSexoAgenda = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblRepositEstadoCivilAgenda = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblRepositCelularAgenda = new javax.swing.JLabel();
        lblUF = new javax.swing.JLabel();
        lblRepositUFAgenda = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblRepositCidadeAgenda = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblRepositBairro = new javax.swing.JLabel();
        lblRepositCPFPacienteAgenda = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblRepositRuaAgenda = new javax.swing.JLabel();
        painelSimulador = new javax.swing.JPanel();
        lblVerificacao = new javax.swing.JLabel();
        barraProgresso = new javax.swing.JProgressBar();
        painelValorTotal = new javax.swing.JPanel();
        lblValorTotal = new javax.swing.JLabel();
        painelDesconto = new javax.swing.JPanel();
        lblDesconto = new javax.swing.JLabel();
        painelTroco = new javax.swing.JPanel();
        lblTroco = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbTipoPagamento = new javax.swing.JComboBox();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setTitle("CAIXA");
        getContentPane().setLayout(null);

        painelPrincipal.setBackground(java.awt.Color.white);
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelSobreMedico.setBackground(java.awt.Color.white);
        painelSobreMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sobre Médico:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        painelSobreMedico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRepositNomeMedicoAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositNomeMedicoAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelSobreMedico.add(lblRepositNomeMedicoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 240, 20));

        lblMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMedico.setForeground(new java.awt.Color(0, 102, 102));
        lblMedico.setText("Médico:");
        painelSobreMedico.add(lblMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        lblEspecialidades.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEspecialidades.setForeground(new java.awt.Color(0, 102, 102));
        lblEspecialidades.setText("Especialidade");
        painelSobreMedico.add(lblEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblIdMedicoAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblIdMedicoAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelSobreMedico.add(lblIdMedicoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 30, 20));

        cbEspecialidadeAgenda.setToolTipText("");
        cbEspecialidadeAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelSobreMedico.add(cbEspecialidadeAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 44, 240, 20));

        painelPrincipal.add(painelSobreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 350, 80));

        painelPaciente1.setBackground(java.awt.Color.white);
        painelPaciente1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sobre Paciente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        painelPaciente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRepositIdPacienteAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositIdPacienteAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositIdPacienteAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, 20));

        lblRepositPacienteAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositPacienteAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositPacienteAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 290, 20));

        lblNomePaciente.setForeground(new java.awt.Color(0, 102, 102));
        lblNomePaciente.setText(" ID     Paciente:  CPF.:");
        painelPaciente1.add(lblNomePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        lblDtNascimento.setForeground(new java.awt.Color(0, 102, 102));
        lblDtNascimento.setText("Data Nascimento:");
        painelPaciente1.add(lblDtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblRepositDtNascimentoAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositDtNascimentoAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepositDtNascimentoAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositDtNascimentoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 90, 20));

        lblSexo.setForeground(new java.awt.Color(0, 102, 102));
        lblSexo.setText("Sexo:");
        painelPaciente1.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        lblRepositSexoAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositSexoAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositSexoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 85, 120, 20));

        lblEstadoCivil.setForeground(new java.awt.Color(0, 102, 102));
        lblEstadoCivil.setText("Estado Civil");
        painelPaciente1.add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        lblRepositEstadoCivilAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositEstadoCivilAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositEstadoCivilAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 85, 90, 20));

        lblCelular.setForeground(new java.awt.Color(0, 102, 102));
        lblCelular.setText("Celular:");
        painelPaciente1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        lblRepositCelularAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositCelularAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositCelularAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 20));

        lblUF.setForeground(new java.awt.Color(0, 102, 102));
        lblUF.setText("UF:");
        painelPaciente1.add(lblUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 112, -1, -1));

        lblRepositUFAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositUFAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositUFAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 30, 20));

        lblCidade.setForeground(new java.awt.Color(0, 102, 102));
        lblCidade.setText("Cidade:");
        painelPaciente1.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 112, -1, -1));

        lblRepositCidadeAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositCidadeAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositCidadeAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, 20));

        lblBairro.setForeground(new java.awt.Color(0, 102, 102));
        lblBairro.setText("Bairro:");
        painelPaciente1.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, -1, -1));

        lblRepositBairro.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 20));

        lblRepositCPFPacienteAgenda.setForeground(java.awt.Color.orange);
        painelPaciente1.add(lblRepositCPFPacienteAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 130, 15));

        lblRua.setForeground(new java.awt.Color(0, 102, 102));
        lblRua.setText("Rua:");
        painelPaciente1.add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 153, -1, -1));

        lblRepositRuaAgenda.setForeground(new java.awt.Color(0, 102, 102));
        lblRepositRuaAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        painelPaciente1.add(lblRepositRuaAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 210, 20));

        painelPrincipal.add(painelPaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 210));

        painelSimulador.setBackground(new java.awt.Color(255, 255, 255));
        painelSimulador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viajando na Núvem:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        painelSimulador.setLayout(null);

        lblVerificacao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblVerificacao.setForeground(new java.awt.Color(0, 102, 102));
        painelSimulador.add(lblVerificacao);
        lblVerificacao.setBounds(10, 90, 430, 17);
        painelSimulador.add(barraProgresso);
        barraProgresso.setBounds(10, 110, 430, 24);

        painelPrincipal.add(painelSimulador, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 450, 160));

        painelValorTotal.setBackground(java.awt.Color.white);
        painelValorTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "R$ Total:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        lblValorTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(0, 102, 102));
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painelValorTotalLayout = new javax.swing.GroupLayout(painelValorTotal);
        painelValorTotal.setLayout(painelValorTotalLayout);
        painelValorTotalLayout.setHorizontalGroup(
            painelValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        painelValorTotalLayout.setVerticalGroup(
            painelValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblValorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        painelPrincipal.add(painelValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 150, 70));

        painelDesconto.setBackground(java.awt.Color.white);
        painelDesconto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "R$ Total Desconto:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        lblDesconto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDesconto.setForeground(new java.awt.Color(0, 102, 102));
        lblDesconto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painelDescontoLayout = new javax.swing.GroupLayout(painelDesconto);
        painelDesconto.setLayout(painelDescontoLayout);
        painelDescontoLayout.setHorizontalGroup(
            painelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(painelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelDescontoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        painelDescontoLayout.setVerticalGroup(
            painelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(painelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelDescontoLayout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(lblDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        painelPrincipal.add(painelDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 150, 70));

        painelTroco.setBackground(java.awt.Color.white);
        painelTroco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "R$ TROCO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        lblTroco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(0, 102, 102));
        lblTroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painelTrocoLayout = new javax.swing.GroupLayout(painelTroco);
        painelTroco.setLayout(painelTrocoLayout);
        painelTrocoLayout.setHorizontalGroup(
            painelTrocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTroco, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        painelTrocoLayout.setVerticalGroup(
            painelTrocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTrocoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelPrincipal.add(painelTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, 70));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DINHEIRO", "CARTAO CREDITO", "CARTAO DEBITO", "TRANSFERENCIA" }));
        jPanel1.add(cbTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 150, 30));

        painelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 200, 90));
        painelPrincipal.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 130, 60));

        getContentPane().add(painelPrincipal);
        painelPrincipal.setBounds(0, 0, 840, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JLabel cbEspecialidadeAgenda;
    private javax.swing.JComboBox cbTipoPagamento;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblDtNascimento;
    private javax.swing.JLabel lblEspecialidades;
    private javax.swing.JLabel lblEstadoCivil;
    public static javax.swing.JLabel lblIdMedicoAgenda;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblNomePaciente;
    public static javax.swing.JLabel lblRepositBairro;
    public static javax.swing.JLabel lblRepositCPFPacienteAgenda;
    public static javax.swing.JLabel lblRepositCelularAgenda;
    public static javax.swing.JLabel lblRepositCidadeAgenda;
    public static javax.swing.JLabel lblRepositDtNascimentoAgenda;
    public static javax.swing.JLabel lblRepositEstadoCivilAgenda;
    public static javax.swing.JLabel lblRepositIdPacienteAgenda;
    public static javax.swing.JLabel lblRepositNomeMedicoAgenda;
    public static javax.swing.JLabel lblRepositPacienteAgenda;
    public static javax.swing.JLabel lblRepositRuaAgenda;
    public static javax.swing.JLabel lblRepositSexoAgenda;
    public static javax.swing.JLabel lblRepositUFAgenda;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblVerificacao;
    private javax.swing.JPanel painelDesconto;
    private javax.swing.JPanel painelPaciente1;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelSimulador;
    private javax.swing.JPanel painelSobreMedico;
    private javax.swing.JPanel painelTroco;
    private javax.swing.JPanel painelValorTotal;
    // End of variables declaration//GEN-END:variables
}
